const icons: any = {
	success: "✔",
	done: "✅",
	doneerror: "⛏️",
	tick: "🗸",
	unchecked: "☐",
	checked: "☑",
	error: "❌",
	ok: "🆗",
	free: "🆓",
	new: "🆕",
	film: "🎞️",
	mic: "🎙️",
	volumeup: "🔊",
	volumedown: "🔈",
	mixer: "🎚️",
	dice: "🎲",
	label: "🏷️",
	break: "🛑",
	breakheart: "💔",
	lamp: "💡",
	zzz: "💤",
	folder: "📁",
	pin: "📌",
	clip: "📎",
	rule: "📏",
	lib: "📕" || "📗" || "📘" || "📙",
	antena: "📡",
	email: "📧",
	letterbox: "📫",
	emptyletterbox: "📭",
	libs: "📚",
	dollar: "💲",
	smartphone: "📱",
	signal: "📶",
	tape: "📼",
	refresh: "🔄",
	joystick: "🕹️",
	mouse: "🖱️",
	keyboard: "⌨️",
	speechballoon: "💬",
	trash: "🗑️",
	map: "🗺️",
	earth: "🌍",
	archive: "🗃️",
	index: "🗂️",
	bookmark: "🔖",
	underconstruction: "🚧",
	siren: "🚨",
	flag: "🚩",
	nosmoke: "🚭",
	shield: "🛡️",
	tool: "🛠️",
	laptop: "💻",
	minidisk: "💽",
	cdrom: "💿",
	stop: "⛔",
	bug: "🐞",
	warn: "⚠️",
	info: " ℹ️",
	heart: "❤️",
	pen: "✒️",
	library: "📚",
	push: "📤",
	pull: "📥",
	commit: "📝",
	branch: "🌱",
	merge: "🔀",
	package: "📦",
	file: "📄",
	save: "💾",
	search: "🔎",
	sign: "✍",
	password: "🔑",
	question: "❓",
	work: "🔨",
	list: "📋",
	star: "⭐",
	item: "📌",
	gear: "⚙️",
	energy: "⚡",
	clock: "⏰",
	arrowleft: "⬅️",
	arrowup: "⬆️",
	arrowdown: "⬇️",
	arrowright: "➡️",
	time: "⏱",
	debug: "🐛",
	terminal: "🖥",
	cloud: "☁",
	rain: "🌧",
	lightning: "🌪",
	cloudsun: "🌤",
	shootingstar: "🌠",
	starshining: "🌟",
	sun: "🌞",
	moon: "🌒",
	play: "▶",
	playpause: "⏯",
	party: "🎉",
	target: "🎯",
	launch: "🚀",
	mosquito: "🦟",
	blood: "🩸",
	bomb: "💣",
	watch: "⌚",
	store: "🏪",
	timer: "⌛",
}

export class Icons {
	private icon: string

	constructor(icon: string) {
		this.icon = icon
	}

	public print(): string {
		return icons[this.icon]
	}
}
